In [64]:
import pandas as pd
import matplotlib.pyplot as plt

In [65]:
df = pd.read_csv('loan_approval_dataset.csv')
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [66]:
df.drop(columns="loan_id",inplace =True)
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [67]:
df.columns = df.columns.str.strip()

print(df.columns)

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [68]:
print(df['education'].unique())
print(df['self_employed'].unique())
print(df['loan_status'].unique())
from sklearn.preprocessing import LabelEncoder
le_education= LabelEncoder()
le_self_employed = LabelEncoder()
le_loan_status = LabelEncoder()
df['education']=le_education.fit_transform(df['education'])
df['self_employed']=le_self_employed.fit_transform(df['self_employed'])
df['loan_status']=le_loan_status.fit_transform(df['loan_status'])

[' Graduate' ' Not Graduate']
[' No' ' Yes']
[' Approved' ' Rejected']

In [69]:
import joblib

joblib.dump(le_education, "le_education.pkl")
joblib.dump(le_self_employed, "le_self_employed.pkl")
joblib.dump(le_loan_status, "le_loan_status.pkl")
print("All files are saved")

All files are saved

In [80]:
from sklearn.model_selection import train_test_split

x = df.drop('loan_status', axis=1)
y = df['loan_status']

X_train, X_test, y_train, y_test = train_test_split( x,y , test_size=0.2, random_state=42)
X_train

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
1675,5,1,0,7900000,29900000,6,568,5800000,13900000,15900000,8700000
1164,0,1,1,9600000,34000000,12,710,23800000,10300000,38100000,7800000
192,1,0,0,800000,2900000,8,682,2200000,1100000,2900000,700000
910,2,0,1,4900000,13100000,18,754,8200000,3300000,16500000,7200000
567,5,0,1,3000000,11100000,12,441,8500000,2500000,7300000,2000000
...,...,...,...,...,...,...,...,...,...,...,...
3444,0,0,1,1300000,4700000,16,530,3200000,1000000,3800000,800000
466,5,1,1,500000,1800000,18,411,1000000,500000,1300000,200000
3092,4,1,1,8600000,20600000,16,449,10800000,10600000,28700000,5400000
3772,2,1,1,7000000,21400000,12,541,3700000,1300000,19800000,9600000
860,4,0,0,6200000,17300000,6,837,12600000,3700000,24700000,4600000

In [90]:
#LogisticRegression
from sklearn.linear_model import  LogisticRegression
from sklearn.metrics  import accuracy_score
LogisticRegression_model=LogisticRegression(max_iter=500)
LogisticRegression_model.fit(X_train, y_train)
y_pred=LogisticRegression_model.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.7985948477751756

In [88]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

y_pred = dt_model.predict(X_test)

print( accuracy_score(y_test, y_pred))

0.977751756440281

In [87]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print( accuracy_score(y_test, y_pred))

0.977751756440281

In [92]:
import joblib

joblib.dump(LogisticRegression_model, "logistic_model.pkl")
joblib.dump(dt_model, "decision_tree_model.pkl")
joblib.dump(rf_model, "random_forest_model.pkl")

print("All models saved successfully!")

All models saved successfully!

In [94]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

In [106]:
from sklearn.model_selection import train_test_split
print(df.columns)
X = df.drop(['loan_amount', 'loan_status'], axis=1)

y = df['loan_amount']
X_train, X_test, y_train, y_test = train_test_split( X,y , test_size=0.2, random_state=42)
X_train

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

,no_of_dependents,education,self_employed,income_annum,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
1675,5,1,0,7900000,6,568,5800000,13900000,15900000,8700000
1164,0,1,1,9600000,12,710,23800000,10300000,38100000,7800000
192,1,0,0,800000,8,682,2200000,1100000,2900000,700000
910,2,0,1,4900000,18,754,8200000,3300000,16500000,7200000
567,5,0,1,3000000,12,441,8500000,2500000,7300000,2000000
...,...,...,...,...,...,...,...,...,...,...
3444,0,0,1,1300000,16,530,3200000,1000000,3800000,800000
466,5,1,1,500000,18,411,1000000,500000,1300000,200000
3092,4,1,1,8600000,16,449,10800000,10600000,28700000,5400000
3772,2,1,1,7000000,12,541,3700000,1300000,19800000,9600000
860,4,0,0,6200000,6,837,12600000,3700000,24700000,4600000

In [108]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.851398066518992

In [110]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

dtR_model = DecisionTreeRegressor(random_state=42)

dtR_model.fit(X_train, y_train)

y_pred = dtR_model.predict(X_test)

print("Decision Tree R2 Score:",
      r2_score(y_test, y_pred))

Decision Tree R2 Score: 0.7127623008900592

In [111]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

rfr_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rfr_model.fit(X_train, y_train)

y_pred = rfr_model.predict(X_test)

print("Random Forest R2 Score:",
      r2_score(y_test, y_pred))

Random Forest R2 Score: 0.8457305216688089

In [112]:
import joblib


joblib.dump(lr_model, "linear_regression_model.pkl")
joblib.dump(dtR_model, "decision_tree_regressor_model.pkl")
joblib.dump(rfr_model, "random_forest_regressor_model.pkl")

print("All 3 models saved successfully!")

All 3 models saved successfully!

In [1]:
import joblib

le_education = joblib.load("le_education.pkl")
print(le_education.classes_)

[' Graduate' ' Not Graduate']

In [2]:
import joblib

le_self_employed = joblib.load("le_self_employed.pkl")
print(le_self_employed.classes_)

[' No' ' Yes']

In [1]:
import joblib

le_loan_status = joblib.load("le_loan_status.pkl")
print(le_loan_status.classes_)

[' Approved' ' Rejected']